name: Generate RSS Feed
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip pyyaml
    - name: Run Generator
      run: python main.py
    - name: Push repo
      run: |
        git config user.name codesandtags
        git config user.email codesandtags@gmail.com
        git add .
        git commit -m "chore: Generating feed automatically"
        git push origin main
    - name: Say goodbye
      run: echo "Your RSS has been generated, now you can check the URL"
      
      
