name: Generate RSS Feed
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Run RSS Generator
      uses: codesandtags/rss-generator-action@main
    - name: Say goodbye
      run: echo "Your RSS has been generated, now you can check the URL"
      
      
